# Site Settings
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# Accessed via {{ site.title }}, {{ site.email }}, and so on.
# Custom variables will be accessible in templates via {{ site.myvariable }}.
title: Prose Poetry
email: little.iron1021@fastmail.com
name: Miguel Pimentel
description: >- # this means to ignore newlines until "baseurl:"
  A look back at my past self.
keywords: [blog, poetry, prose-poetry]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://semanticdata.github.io/jekyll-paper" # base hostname & protocol, e.g. http://example.com
domain: "Miguel Pimentel" # domain name for site, e.g. example.com
language: [en, es]
# Supported languages list:
# es: Español (Spanish)
# fr: Français (French)

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

paginate: 20
paginate_path: "/page:num/"

comments: false # enable comments
disqus: # disqus account

mathjax: false # Mathematics
mermaid: false # Diagrams

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Category settings
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
